### ISSUE TITLE
Channel Access Code Invalid? [April 2024]

### ISSUE THREAD

**Issue by dlasher** [evuraan/MythicalMythTV#12]
![Screen Shot 2024-04-10 at 12 27 48 PM](https://github.com/evuraan/MythicalMythTV/assets/937979/41c729fd-9c9f-40a4-af6c-911dafd2b3ce)

Current "beta" code no longer valid?

**Comment by evuraan** [comment]
thanks @dlasher , the beta channel expired, I will look into this soon. 

until then, also available is the trial player:  https://channelstore.roku.com/details/89459fb0cfac7e876489853ba8009675/mythical-mythtv-trial-player

**Comment by evuraan** [comment]
[Mythical MythTV Beta Channel](https://my.roku.com/account/add/MythicalMythTVBeta) should be back now. 

I've also added a way to change the maestro url w/o having to reinstall - 

![roku_which_way](https://github.com/evuraan/MythicalMythTV/assets/39205936/7be07547-a482-4824-9df4-dafc106c2558)

**Comment by dlasher** [comment]
Thank you @evuraan  - I will give it a shot this weekend - several generations of Roku's to test with.

**Comment by dlasher** [comment]
**Closing this ticket** - app up and running - will open new ticket on issue(s) experienced.
