### ISSUE TITLE
FEATURE REQUEST: Detailed Debug

### ISSUE THREAD

**Issue by dlasher** [evuraan/MythicalMythTV#14]
Configuration:
* mythTV container - running ubuntu22 - 10.4.10.100
* maestro container - running ubuntu22 -  using ` -mythBE 10.4.10.100:6544 -ignoreDelete -onTheFly -debug` and `/myth/tv` folder mounted via NFS.

Any way to get extended debug information from maestro? already using the -debug flag, but not seeing any console output during playback attempts, media browsing, etc.

```
Found 1061_20131003210100.mpg
Found 1021_20131001210100.mpg
Found 1061_20130926210100.mpg
Found 1021_20130924210100.mpg
Found 1061_20130111210000.mpg
Found 1186 recordings
Listening on:
  1  http://127.0.0.1:8080/
  2  http://10.4.10.207:8080/
```

**Current Status: App can browse parent folders, browse individual programs, but any playback starts, gets to 13%, and never proceeds.**

**Comment by evuraan** [comment]
@dlasher, thanks for this report!  Please try the <s>7.1a</s> latest build from branch [maestro_7.1a](https://github.com/evuraan/MythicalMythTV/tree/maestro_7.1a/maestro/bin) and let me know how it looks on your end. I think I was calling the transcode done a little too early; fixed now. 

Pls note, the options have [changed](https://github.com/evuraan/MythicalMythTV/blob/maestro_7.1a/maestro/README.md#usage),  `-onTheFly` is now the [default mode](https://github.com/evuraan/MythicalMythTV/blob/maestro_7.1a/maestro/README.md) and you no longer need to specify it. So in your case, it will now be `-mythBE 10.4.10.100:6544 -ignoreDelete -debug -pickupFolder /myth/tv`.

**Comment by dlasher** [comment]
NP - thanks for the project, looking forward to having it in a usable state for me.

Suggestions on how to address #15  ? I can't test the changes here till I fix that.

**Comment by dlasher** [comment]
On this issue, tested on a different roku - (primary one still corrupted settings) -- included all changes recommended, including baseURL, and I can connect, browse content, getting nice still images of the program, but playback now doesn't even start. Click, back to program list. Click, back to program list.

Still nothing in console output. Would be awesome to turn up a debug level somehow there, at least show how far we're getting.

**Comment by evuraan** [comment]
Let's continue in your other thread. do you have ffmpeg installed in your path there? I think you just need to relaunch the app!
