### ISSUE TITLE
BUG: Hitting "back" on settings appears to corrupt settings. 

### ISSUE THREAD

**Issue by dlasher** [evuraan/MythicalMythTV#15]
It appears possible in current version to make the app unusable by backing out of settings.

Steps:
1. set settings correctly.
2. validate that you can navigate content
3. leave app
4. open app - choose "settings"
5. hit the "BACK" button - bailing out of settings, app closes

Now you're hosed.
* open app - choose "watch" - app closes
* open app - choose "settings" - set settings correctly - app closes
* app will close on "watch" attempts no matter what else you do.

:sad face:

**Comment by dlasher** [comment]
Did try uninstalling / reinstalling App - no love.

**Comment by evuraan** [comment]
1. What do you set your `-maestroBaseURL` cli option to?  
2. On the roku, what are you setting your `maestroBaseURL` to? [Ref1](https://github.com/evuraan/MythicalMythTV/blob/main/images/maestro_baseURL.jpg) [Ref2](https://github.com/evuraan/MythicalMythTV/blob/main/images/maetroConfirm.jpg)

From your #14, looks like your maestro listens on `http://10.4.10.207:8080/` - if this is your roku's  `maestroBaseURL`, you either need to specify `-maestroBaseURL http://10.4.10.207:8080/` in cli, or, if you are not setting this, you must have a _local_ DNS entry for `maestro` roku can resolve correctly:

In my case, 
<pre>
$ host maestro 192.168.1.31
Using domain server:
Name: 192.168.1.31
Address: 192.168.1.31#53
Aliases: 

maestro has address 192.168.1.13
</pre>

**Comment by dlasher** [comment]
> 1. What do you set your `-maestroBaseURL` cli option to?

I didn't change it on the server side.  Maestro is listening on (4) different addresses, including one on the same vlan with the Roku 

> 2. On the roku, what are you setting your `maestroBaseURL` to? [Ref1]

http://10.4.10.227:8080
> From your #14, looks like your maestro listens on `http://10.4.10.207:8080/` - if this is your roku's `maestroBaseURL`, you either need to specify `-maestroBaseURL http://10.4.10.207:8080/` in cli, or, if you are not setting this, you must have a _local_ DNS entry for `maestro` roku can resolve correctly:

Ahh - ok, let me set that. I was assuming it was listening on all available interfaces?

```
Listening on:
  1  http://127.0.0.1:8080/
  2  http://10.4.10.207:8080/
  3  http://198.18.52.207:8080/
  4  http://10.4.23.207:8080/
```

**Comment by dlasher** [comment]
Sadly, no change in behavior. Primary Roku still "crashes" app, flips back to Roku App screen.

**Comment by evuraan** [comment]
can you add logs / screenshots / photos? There is a `-debug` flag you can add to the cli 

![image](https://github.com/evuraan/MythicalMythTV/assets/39205936/5a961aeb-3c45-40d8-803c-95d88c1da232)
