### ISSUE TITLE
failed to build data from backend

### ISSUE THREAD

**Issue by tonyguadagno** [evuraan/MythicalMythTV#2]
hi, not sure what i am doing wrong, but this is what happens, can you point me in the right direction?

i am running maestro on my Mythtv backend:

./maestro-linux-amd64 -maestroBaseURL "http://maestro.domain.org:55555" -onTheFly
Warning: No recordings found
Failed to build data from backend 127.0.0.1:6544

as you can see, my backend is listening on 6544

root@HomeMythBackend:/opt/MythicalMythTV/maestro/bin# netstat -na |grep :6544
tcp        0      0 0.0.0.0:6544            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:57222         127.0.0.1:6544          TIME_WAIT
tcp6       0      0 :::6544                 :::*                    LISTEN

**Comment by evuraan** [comment]
Please add  `-debug` flag and see more info about what is going on.  Also, what's your mythBE version, how long has it been running?

**Comment by tonyguadagno** [comment]
hi, here is the version
mythtv-backend-master/now 2:33.1+fixes.202307280403.9572dc5a12~ubuntu22.04.1 all

and here is the debug

>  ./maestro-linux-amd64 -maestroBaseURL "http://maestro.domain.org:55555" -onTheFly -debug
Skipping 1241_20230821030000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230820203000.ts, min size is 10000, got 0 on disk
Skipping 1311_20230820143000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230820143000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230820033000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230817010000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230817000000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230814030000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230810000000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230807030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230807020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230807010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230807000000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230806000000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230803000000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230731030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230731020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230731010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230731000000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230728010000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230727000000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230724030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230724010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230724000000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230721010000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230720000000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230717030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230717010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230717000000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230714010000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230713000000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230710030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230710010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230707010000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230706000000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230703030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230703010000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230629000000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230626030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230626010000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230623043000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230622000000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230619010000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230615000000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230608000000.ts, min size is 10000, got 0 on disk
Skipping 1311_20230602010000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230601000000.ts, min size is 10000, got 0 on disk
Skipping 1311_20230526013000.ts, min size is 10000, got 0 on disk
Skipping 1081_20230523020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230522010000.ts, min size is 10000, got 0 on disk
Skipping 1081_20230516020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230515010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230511010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230509183000.ts, min size is 10000, got 0 on disk
Skipping 1081_20230509020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230509010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230508183000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230508010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230505183000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230505013000.ts, min size is 10000, got 0 on disk
Skipping 1311_20230505010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230504183000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230504010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230503183000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230503020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230503010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230503000000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230502183000.ts, min size is 10000, got 0 on disk
Skipping 1081_20230502020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230501183000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230501010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230428183000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230428013000.ts, min size is 10000, got 0 on disk
Skipping 1311_20230428010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230427183000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230427010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230426183000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230426020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230426010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230426000000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230425183000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230424183000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230424010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230421183000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230421013000.ts, min size is 10000, got 0 on disk
Skipping 1311_20230421010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230419020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230419010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230419000000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230417010000.ts, min size is 10000, got 0 on disk
Skipping 1311_20230414010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230413010000.ts, min size is 10000, got 0 on disk
Skipping 1081_20230411020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230410010000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230407013000.ts, min size is 10000, got 0 on disk
Skipping 1311_20230407010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230405000000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230403010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230329020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230329010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230329000000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230327010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230322010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230322000000.ts, min size is 10000, got 0 on disk
Skipping 1081_20230321020000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230320030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230320010000.ts, min size is 10000, got 0 on disk
Skipping 1311_20230317010000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230313030000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230309020000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230306041000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230302020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230301020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230301010000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230227040000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230223020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230223020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230222020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230222010000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230220040000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230216020000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230216020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230215020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230215010000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230213040000.ts, min size is 10000, got 0 on disk
Skipping 1211_20230209020000.ts, min size is 10000, got 0 on disk
Skipping 1132_20230209020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230201020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230201010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230125020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230125010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230118020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230118010000.ts, min size is 10000, got 0 on disk
Skipping 1241_20230115040000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230111020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230111010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230104020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20230104010000.ts, min size is 10000, got 0 on disk
Skipping 1212_20221229130000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221228020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221217030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221217020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221205030000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221205020000.ts, min size is 10000, got 0 on disk
Skipping 1132_20221201020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221130030000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221123030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221120040000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221117020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221116030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221113040000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221107030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221106030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221103010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221102020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221031020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221030030000.ts, min size is 10000, got 0 on disk
Skipping 1241_20221028040000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221027010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221026020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221024020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221023030000.ts, min size is 10000, got 0 on disk
Skipping 1241_20221021040000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221020010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221019020000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221017020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221016030000.ts, min size is 10000, got 0 on disk
Skipping 1241_20221014040000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221013010000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221012020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221010010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221009030000.ts, min size is 10000, got 0 on disk
Skipping 1241_20221007040000.ts, min size is 10000, got 0 on disk
Skipping 1131_20221005020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221003010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20221002030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220929010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220926010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220925030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220918030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220912010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220911030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220905010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220904030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220829050000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220829020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220828030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220821030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220815020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220814030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220808020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220807030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220801020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220731030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220725020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220718020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220711020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220523010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220516010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220509010000.ts, min size is 10000, got 0 on disk
Skipping 1212_20220406010000.ts, min size is 10000, got 0 on disk
Skipping 1212_20220330010000.ts, min size is 10000, got 0 on disk
Skipping 1213_20220330000000.ts, min size is 10000, got 0 on disk
Skipping 1212_20220323010000.ts, min size is 10000, got 0 on disk
Skipping 1212_20220316010000.ts, min size is 10000, got 0 on disk
Skipping 1212_20220309020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20220113020000.ts, min size is 10000, got 0 on disk
Skipping 1132_20211212010000.ts, min size is 10000, got 0 on disk
Skipping 1241_20211114040000.ts, min size is 10000, got 0 on disk
Skipping 1241_20211024030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20210930010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20210916010000.ts, min size is 10000, got 0 on disk
Skipping 1313_20210911190000.ts, min size is 10000, got 0 on disk
Skipping 1211_20210819010000.ts, min size is 10000, got 0 on disk
Skipping 1211_20210819000000.ts, min size is 10000, got 0 on disk
Skipping 1213_20210604163500.ts, min size is 10000, got 0 on disk
Skipping 1241_20210603190000.ts, min size is 10000, got 0 on disk
Skipping 1241_20210603060000.ts, min size is 10000, got 0 on disk
Skipping 1213_20210421000200.ts, min size is 10000, got 0 on disk
Skipping 1211_20210330010200.ts, min size is 10000, got 0 on disk
Skipping 1241_20210321040000.ts, min size is 10000, got 0 on disk
Skipping 1211_20201213030000.ts, min size is 10000, got 0 on disk
Skipping 1241_20201212060000.ts, min size is 10000, got 0 on disk
Skipping 1211_20201123020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20201116020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20201114080000.ts, min size is 10000, got 0 on disk
Skipping 1211_20201109030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20201102030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20201026020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20201019020000.ts, min size is 10000, got 0 on disk
Skipping 1211_20201012020000.ts, min size is 10000, got 0 on disk
Skipping 1213_20200908223000.ts, min size is 10000, got 0 on disk
Skipping 1213_20200907223000.ts, min size is 10000, got 0 on disk
Skipping 1213_20200905223000.ts, min size is 10000, got 0 on disk
Skipping 1213_20200904223000.ts, min size is 10000, got 0 on disk
Skipping 1213_20200903223000.ts, min size is 10000, got 0 on disk
Skipping 1213_20200902223000.ts, min size is 10000, got 0 on disk
Skipping 1213_20200901223000.ts, min size is 10000, got 0 on disk
Skipping 1213_20200901003000.ts, min size is 10000, got 0 on disk
Skipping 1314_20200516030000.ts, min size is 10000, got 0 on disk
Skipping 1101_20200224040000.ts, min size is 10000, got 0 on disk
Skipping 1213_20191216004200.ts, min size is 10000, got 0 on disk
Skipping 1241_20191006030000.ts, min size is 10000, got 0 on disk
Skipping 1313_20190420200000.ts, min size is 10000, got 0 on disk
Skipping 1313_20190122150000.mpg, min size is 10000, got 0 on disk
Skipping 1211_20181217010000.ts, min size is 10000, got 0 on disk
Skipping 1212_20181215020000.ts, min size is 10000, got 0 on disk
Skipping 1241_20181123010000.ts, min size is 10000, got 0 on disk
Skipping 1241_20181116010000.ts, min size is 10000, got 0 on disk
Skipping 1313_20180705060000.mpg, min size is 10000, got 0 on disk
Skipping 1313_20180618040100.mpg, min size is 10000, got 0 on disk
Skipping 1211_20180605000000.mpg, min size is 10000, got 0 on disk
Skipping 1313_20180527160000.ts, min size is 10000, got 0 on disk
Skipping 1131_20180523003000.mpg, min size is 10000, got 0 on disk
Skipping 1102_20180506000000.mpg, min size is 10000, got 0 on disk
Skipping 1313_20180413060000.ts, min size is 10000, got 0 on disk
Skipping 1311_20180322000000.mpg, min size is 10000, got 0 on disk
Skipping 1313_20180318060000.mpg, min size is 10000, got 0 on disk
Skipping 1313_20180318040000.mpg, min size is 10000, got 0 on disk
Skipping 1313_20180318020000.mpg, min size is 10000, got 0 on disk
Skipping 1311_20180315000000.mpg, min size is 10000, got 0 on disk
Skipping 1313_20180312220000.mpg, min size is 10000, got 0 on disk
Skipping 1311_20180308010000.mpg, min size is 10000, got 0 on disk
Skipping 1313_20180307070000.ts, min size is 10000, got 0 on disk
Skipping 1311_20180301010000.mpg, min size is 10000, got 0 on disk
Skipping 1681_20180217020300.mpg, min size is 10000, got 0 on disk
Skipping 1311_20180208010000.mpg, min size is 10000, got 0 on disk
Skipping 1311_20180201010000.mpg, min size is 10000, got 0 on disk
Skipping 1311_20180125010000.mpg, min size is 10000, got 0 on disk
Skipping 1313_20180120150000.mpg, min size is 10000, got 0 on disk
Skipping 1311_20180118010000.mpg, min size is 10000, got 0 on disk
Skipping 1311_20180104010000.mpg, min size is 10000, got 0 on disk
Skipping 1211_20171203033000.ts, min size is 10000, got 0 on disk
Skipping 1241_20170918030000.ts, min size is 10000, got 0 on disk
Skipping 1211_20170731020000.mpg, min size is 10000, got 0 on disk
Skipping 1211_20170724020000.mpg, min size is 10000, got 0 on disk
Skipping 1211_20170717020000.mpg, min size is 10000, got 0 on disk
Skipping 1211_20161127023000.mpg, min size is 10000, got 0 on disk
Skipping 1311_20160223010000.mpg, min size is 10000, got 0 on disk
Skipping 1311_20160216010000.mpg, min size is 10000, got 0 on disk
Skipping 1311_20160209010000.mpg, min size is 10000, got 0 on disk
Skipping 1311_20160207010000.mpg, min size is 10000, got 0 on disk
Skipping 1311_20160202010000.mpg, min size is 10000, got 0 on disk
Warning: No recordings found
Failed to build data from backend 127.0.0.1:6544
Skipping 1311_20160126010000.mpg, min size is 10000, got 0 on disk

**Comment by evuraan** [comment]
- Do those `.mpg,.ts` files exist in your `pickupFolder`  default `"/var/lib/mythtv/recordings"` ? 
- Does the user running `maestro` has read access to those files?

**Comment by tonyguadagno** [comment]
i think i might know whats going on.  first, for the test, i was running root, so perms should not be an issue...however.  I have storage groups set up and i put my files in a different directory.  it sounds like you are not reading the defined storage group for the recordings but going to the default instead?

i think for this to work, you will need to get the list of defined storage group from the backend and look there.

**Comment by evuraan** [comment]
```bash
  -pickupFolder string
        folder containing playable video files and thumbnails (default "/var/lib/mythtv/recordings"
```
Won't this option work for you in this case? You can point to the folder.

**Comment by tonyguadagno** [comment]
hi, yes, that will work as a temporary solution, however, i have files in different locations...so it would be best if you added a feature to get the path for each file from the db.

but there seams to be another...bigger issue:  it seem that the -maestroBaseURL is being ignored:

root@HomeMythBackend:/opt/MythicalMythTV/maestro/bin# ./maestro-linux-amd64 -maestroBaseURL "http://maestro.domain.org:55555" -onTheFly -pickupFolder "/recordings/RecordedTV"
Listening on:
  1  http://127.0.0.1:8080/
  2  http://192.168.168.13:8080/
err: listen tcp :8080: bind: address already in use


i have defined port 55555 because my 8080 is already in use.  you seem to be ignoring this....do you want me to open a new ticket just on this?
thanks

**Comment by evuraan** [comment]
Thanks for the  feedback! Sorry, at this time, the beta roku channel [expects](https://github.com/evuraan/MythicalMythTV/blob/main/maestro/README.md#connectivity-to-maestro) to connect to port `:8080` of the maestro endpoint .  

If you can get to listen on 8080, you are quite close:

```bash
$ ./maestro -debug -onTheFly -pickupFolder "/recordings/RecordedTV" -maestroBaseURL  http://192.168.168.13:8080/ 
```
(PS: don't have to run as root.! [ref](https://github.com/evuraan/MythicalMythTV/tree/main/maestro#running-maestro))

>  i have files in different locations

We gave up DB access to simplify; won't be deducing storage paths. Instead, `maestro` expects media files inside `pickupFolder` at this time. There are creative ways to achieve this: provide symlinks to your `.mpg|.ts|.png` files in a folder and use this folder as your `pickupFolder`; `maestro` follows symlinks.

**Comment by tonyguadagno** [comment]
hi, well, that is disappointing.  i cannot use this until you allow me to pick the port.

can i put in a feature request?  i would not imagine it is that hard to code that as a command line variable?

anyway, thanks for your efforts.

**Comment by evuraan** [comment]
> can i put in a feature request? 

Have at it! 

> i would not imagine it is that hard to code that as a command line variable?

It is not the cli, it is the roku app trying to connect to port 8080. you can already specify an alt listening port by using the `-port` arg on the cli. Try running `maestro` with the `-h` option and see for yourself. 
```bash
  -port int
        server port (default 8080)
```
Following along this route, depending on your comfort/skill level you may try this out:

let's say you are now listening on port 8081:

```bash
$ ./maestro -debug -onTheFly -pickupFolder "/recordings/RecordedTV" -maestroBaseURL  http://192.168.168.13:8080/ -port 8081
```

Suppose your roku TV is at `192.168.168.100` - you can try all requests from  `192.168.168.100` to `192.168.168.13:8080` rerouted to `192.168.168.13:8081`:

```bash
net.ipv4.ip_forward=1
iptables -t nat -A PREROUTING -p tcp -d 192.168.168.13 --dport 8080 -s 192.168.168.100 -j DNAT --to-destination 192.168.168.13:8081
```

This may work, google/[chat](https://chat.openai.com/) may help - but again, YMMV! But thanks for trying, I appreciate your feedback and viewpoint.

**Comment by evuraan** [comment]
Update:

I've pushed out an update which will let you configure the `maestroBaseURL` to your liking (with alternate port). 

See https://github.com/evuraan/MythicalMythTV/tree/main/maestro#connectivity-to-maestro for more info: 

![image](https://github.com/evuraan/MythicalMythTV/assets/39205936/e9d2f43f-45ca-4e57-891f-68750c8eac55)

![image](https://github.com/evuraan/MythicalMythTV/assets/39205936/d329a5f0-569d-4218-b9ce-1383f9d8334a)

**Comment by tonyguadagno** [comment]
> I've pushed out an update which will let you configure the `maestroBaseURL` to your liking (with alternate port).

hi, sorry if i am being dense, but i do not see the update.  it looks like the bin's have not been updated in the past 2 weeks.?

**Comment by evuraan** [comment]
The roku channel was updated. The standalone binary already has the option you need, `-port` to specify the alternate port. Try the `-h` option and see for yourself:

![image](https://github.com/evuraan/MythicalMythTV/assets/39205936/d5dae537-4c5a-4287-91d1-f3066bd52165)

**Comment by evuraan** [comment]
re-opening, let's see if we can retrieve the storage directories from the API. 

Since you have many folders, what does your 
`http://mythBand:6544/Myth/GetStorageGroupDirs`  show?

**Comment by tonyguadagno** [comment]
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<StorageGroupDirList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" serializerVersion="1.1">
<StorageGroupDirs>
<StorageGroupDir>
<Id>9</Id>
<GroupName>Banners</GroupName>
<HostName>HomeMythBackend</HostName>
<DirName>/recordings/Banners/</DirName>
<DirRead>true</DirRead>
<DirWrite>true</DirWrite>
<KiBFree>1188796004</KiBFree>
</StorageGroupDir>
<StorageGroupDir>
<Id>15</Id>
<GroupName>ChannelIcons</GroupName>
<HostName>HomeMythBackend</HostName>
<DirName>/recordings/ChannelIcons</DirName>
<DirRead>true</DirRead>
<DirWrite>true</DirWrite>
<KiBFree>1188796004</KiBFree>
</StorageGroupDir>
<StorageGroupDir>
<Id>6</Id>
<GroupName>Coverart</GroupName>
<HostName>HomeMythBackend</HostName>
<DirName>/recordings/CoverArt/</DirName>
<DirRead>true</DirRead>
<DirWrite>true</DirWrite>
<KiBFree>1188796004</KiBFree>
</StorageGroupDir>
<StorageGroupDir>
<Id>2</Id>
<GroupName>DB Backups</GroupName>
<HostName>HomeMythBackend</HostName>
<DirName>/recordings/DBBackups/</DirName>
<DirRead>true</DirRead>
<DirWrite>true</DirWrite>
<KiBFree>1188796004</KiBFree>
</StorageGroupDir>
<StorageGroupDir>
<Id>11</Id>
<GroupName>Default</GroupName>
<HostName>HomeMythBackend</HostName>
<DirName>/recordings/RecordedTV</DirName>
<DirRead>true</DirRead>
<DirWrite>true</DirWrite>
<KiBFree>1188796004</KiBFree>
</StorageGroupDir>
<StorageGroupDir>
<Id>7</Id>
<GroupName>Fanart</GroupName>
<HostName>HomeMythBackend</HostName>
<DirName>/recordings/FanArt/</DirName>
<DirRead>true</DirRead>
<DirWrite>true</DirWrite>
<KiBFree>1188796004</KiBFree>
</StorageGroupDir>
<StorageGroupDir>
<Id>1</Id>
<GroupName>LiveTV</GroupName>
<HostName>HomeMythBackend</HostName>
<DirName>/recordings/LiveTV/</DirName>
<DirRead>true</DirRead>
<DirWrite>true</DirWrite>
<KiBFree>1188796004</KiBFree>
</StorageGroupDir>
<StorageGroupDir>
<Id>10</Id>
<GroupName>Music</GroupName>
<HostName>HomeMythBackend</HostName>
<DirName>/recordings/Music/</DirName>
<DirRead>true</DirRead>
<DirWrite>true</DirWrite>
<KiBFree>1188796004</KiBFree>
</StorageGroupDir>
<StorageGroupDir>
<Id>12</Id>
<GroupName>MusicArt</GroupName>
<HostName>HomeMythBackend</HostName>
<DirName>/recordings/Music</DirName>
<DirRead>true</DirRead>
<DirWrite>true</DirWrite>
<KiBFree>1188796004</KiBFree>
</StorageGroupDir>
<StorageGroupDir>
<Id>13</Id>
<GroupName>Photographs</GroupName>
<HostName>HomeMythBackend</HostName>
<DirName>/recordings/Pictures/</DirName>
<DirRead>true</DirRead>
<DirWrite>true</DirWrite>
<KiBFree>1188796004</KiBFree>
</StorageGroupDir>
<StorageGroupDir>
<Id>14</Id>
<GroupName>RecordedTV</GroupName>
<HostName>HomeMythBackend</HostName>
<DirName>/recordings/RecordedTV/</DirName>
<DirRead>true</DirRead>
<DirWrite>true</DirWrite>
<KiBFree>1188796004</KiBFree>
</StorageGroupDir>
<StorageGroupDir>
<Id>8</Id>
<GroupName>Screenshots</GroupName>
<HostName>HomeMythBackend</HostName>
<DirName>/recordings/ScreenShots/</DirName>
<DirRead>true</DirRead>
<DirWrite>true</DirWrite>
<KiBFree>1188796004</KiBFree>
</StorageGroupDir>
<StorageGroupDir>
<Id>5</Id>
<GroupName>Trailers</GroupName>
<HostName>HomeMythBackend</HostName>
<DirName>/recordings/Trailers/</DirName>
<DirRead>true</DirRead>
<DirWrite>true</DirWrite>
<KiBFree>1188796004</KiBFree>
</StorageGroupDir>
<StorageGroupDir>
<Id>4</Id>
<GroupName>Videos</GroupName>
<HostName>HomeMythBackend</HostName>
<DirName>/recordings/Video/</DirName>
<DirRead>true</DirRead>
<DirWrite>true</DirWrite>
<KiBFree>1188796004</KiBFree>
</StorageGroupDir>
</StorageGroupDirs>
</StorageGroupDirList>
```

**Comment by evuraan** [comment]
Thanks, let's track this separately in #7.
