### ISSUE TITLE
description format isssues

### ISSUE THREAD

**Issue by tonyguadagno** [evuraan/MythicalMythTV#4]
first, let me say that i really appreciate what you are doing here.  i hope these testing results are helpful to you.

i have this working and i noticed some "opportunities for improvement".

1. the list includes deleted recordings...i would rather it not
2. the formatting for the episode description overlaps the episode list.  it would be nice to segregate these into different sections of the screen
![PXL_20230828_174138794](https://github.com/evuraan/MythicalMythTV/assets/25204879/02d5e205-fe24-437c-8716-76306cb63cc3)

**Comment by evuraan** [comment]
> i have this working and i noticed some "opportunities for improvement".

Bravo! Well done,  you got this far! 

> the list includes deleted recordings...i would rather it not

Can you please expand on this, so I that understand:  Are those recordings deleted by this app or elsewhere? i.e., you deleted recordings for example, using `mythweb` and they still showing up in here? If so, are you able to play those, or, they are just being listed?

**Comment by evuraan** [comment]
PS: Thanks for the image, made my day! :)

**Comment by tonyguadagno** [comment]
> Can you please expand on this, so I that understand: Are those recordings deleted by this app or elsewhere? i.e., you deleted recordings for example, using `mythweb` and they still showing up in here? If so, are you able to play those, or, they are just being listed?

sorry, when you delete a recording in Myth, it is in a "deleted group" for 2 days before being purged.  during this time, myth frontend will not show the recording unless you change the group filter.  this is so you can undelete it if you want.

you are showing recordings that are in the "deleted group" but not yet purged.

**Comment by evuraan** [comment]
The Services API currently returns to us items in `"deleted group"` too, does not seem like there is a way to tell them apart - unless we query the mysql DB - which we used to do. We [relinquished DB access,](https://github.com/evuraan/MythicalMythTV/blob/main/Changelog.md#2023-08-14) and currently there are no plans to go back that route - that's one less credential requirement and access level to deal with. 

If delete is requested through `maestro`, it maintains state (until restarted), so it will not show items where a delete has been requested on. (Please make sure you've the latest bin build.)

Optionally, we can file a feature request upstream with `mythtv-devs`  to refine this current behavior.

**Comment by evuraan** [comment]
> the episode description overlaps the episode list

The channel has been updated to improve the layout, please update and give it a try.

**Comment by tonyguadagno** [comment]
looks much better, thanks!
