### ISSUE TITLE
Please implement groups

### ISSUE THREAD

**Issue by tonyguadagno** [evuraan/MythicalMythTV#5]
hi, I just watched a recording and seemed to go well.  however, I think that groups are more than a "nice to have"...I have about 300 recordings.  If you do not organize the recordings into groups (ie titles) then if I want to watch something older (pretty common) I might have to down arrow as much as 150 times to get to the recording.

I am not sure how hard this would be, but i think it is pretty important.

thanks

**Comment by tonyguadagno** [comment]
hi, it just occurred to me that you might want to reach out to peter bennett.  he is on the mythtv mailing lists and a developer.  he wrote the firestick version (mythleanfront) and i think he did that all via the API as well.  he have the listings grouped etc, he might be able to help???

just a thought

**Comment by evuraan** [comment]
@tonyguadagno, hope you're keeping well in 2024! 

groups have been added, [more info](https://github.com/evuraan/MythicalMythTV/blob/mime_and_group_support/maestro/groups.md). 

Try the [updated maestro binary](https://github.com/evuraan/MythicalMythTV/tree/mime_and_group_support/maestro/bin) along with updated [Roku Beta Channel. ](https://my.roku.com/account/add/MythicalMythTVBeta).

Please let me know if you have any feedback.
