### ISSUE TITLE
FF and RW don't seem to work

### ISSUE THREAD

**Issue by tonyguadagno** [evuraan/MythicalMythTV#6]
when i am playing, if i FF or RW, it just seems to go back to a Paused state, it will not FF or RW.

thanks

**Comment by evuraan** [comment]
If you use on the fly encoding with the `-onTheFly` flag, this is a trade-off: we cannot wait until the transcoding finishes to begin playback.  If you need seek capability, you will need to pre-cook your videos with a valid `moov atom`. 

https://github.com/evuraan/MythicalMythTV/tree/main/maestro#pre-processing-your-videos
